services:
  postgres:
    image: postgres:16-alpine
    container_name: agrolink-postgres
    environment:
      POSTGRES_DB: agrolinkdb
      POSTGRES_USER: agrolinkadmin
      POSTGRES_PASSWORD: agrolinkpassword
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20

  pgadmin:
    image: elestio/pgadmin:latest
    container_name: agrolink-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

  minio:
    image: minio/minio:latest
    container_name: agrolink-minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API-compatible endpoint
      - "9001:9001"   # MinIO Console
    volumes:
      - minio_data:/data

  minio-setup:
    image: minio/mc:latest
    container_name: agrolink-minio-setup
    depends_on:
      - minio
    entrypoint: ["/bin/sh", "-c"]
    command: |
      mc alias set local http://minio:9000 minio minio12345 && \
      mc mb -p local/agrolink-spa-bucket || true && \
      mc mb -p local/agrolink-storage-bucket || true && \
      mc anonymous set public local/agrolink-spa-bucket || true && \
      echo "MinIO buckets created"


volumes:
  pg_data:
  minio_data:
